version: "2"
services:

  fluentdimage:
    container_name: fluentd
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - logger:/fluentdlog
    networks:
      - omni
    ports:
      - "24224:24224"
    stdin_open: true

volumes:
  logger:
    driver: local

networks:
  omni:
    external:
      name: omni-network
